//// <auto-generated />
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
////using OurDogs.Data;

//#nullable disable

//namespace FEH.Migrations
//{
//    [DbContext(typeof(FEHContext))]
//    [Migration("20241206220512_DogsList")]
//    partial class DogsList
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.11")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("FEH.Components.Dogs", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<bool>("AdoptionPending")
//                        .HasColumnType("bit");

//                    b.Property<int>("Age")
//                        .HasColumnType("int");

//                    b.Property<string>("Breed")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Description")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Image")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<decimal>("Size")
//                        .HasColumnType("decimal(18,2)");

//                    b.HasKey("Id");

//                    b.ToTable("Dogs");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
